### ISSUE TITLE
Portainer 1.24.0 with Home Assistant and Raspberry Pi

### ISSUE THREAD

**Issue by olaxe** [technorabilia/portainer-templates#1]
Hello,

When I add the URL and go to App Templates, I have the following error message:
Failure: Json cannot unmarshal object into Go value of type []portainer.Template

**Comment by snauth** [comment]
Same problem here with portainer 1.22.1 installed on docker 20.10.05 directly without home assistant.

**Comment by technorabilia** [comment]
@olaxe @snauth
Sorry about that. Note that at the moment only Portainer v2 is supported.

If I have time I will have a look if I can also generate the templates for Portainer v1.

In [this](https://github.com/portainer/templates) repository you can see the difference between the templates-1.20.0.json schema that you need and templates-2.0.json schema that I am generating.

**Comment by technorabilia** [comment]
@olaxe @snauth 
Could you please try the following url?
https://raw.githubusercontent.com/technorabilia/portainer-templates/main/lsio/templates/templates-1.20.0.json
Tested on Portainer 1.24.2.

**Comment by snauth** [comment]
@technorabilia  Thanks for this! I used this opportunity to upgrade portainer to 2.0 (and cannot test the 1.X file any longer).
