### ISSUE TITLE
Would it possible to merge the default app template list to this one ?

### ISSUE THREAD

**Issue by jpmurray** [technorabilia/portainer-templates#2]
Well, maybe it's done already, but since we can't have multiple URL for app templates in Portainer, would it be possible to merge the default one with yours?

I like the idea of get more templates, but I do like the default ones also ! ;-)

**Comment by technorabilia** [comment]
@jpmurray 
Maybe you can take a look at the repo below? I think this is pretty close to what you're looking for.
https://github.com/technorabilia/portainer-tools

**Comment by jpmurray** [comment]
Definitely! Thanks for the link !
