### ISSUE TITLE
Description of PUID and PGID are reversed

### ISSUE THREAD

**Issue by huettenwirt** [technorabilia/portainer-templates#6]
...just a minor cosmetic one, but the descriptions for PUID and PGID are reversed. 

Best regards!

**Comment by technorabilia** [comment]
Hey thanks, you're the first to notice!

I modified it and it should be processed in the next workflow run...

**Comment by huettenwirt** [comment]
You're welcome ;-)

I just installed your portainer-tools and was on a search & replace trip
with Notepad++ to tweak your list to my needs (UID, GID, Path) and there I
came across this...

Btw. this S&R is the only way to get an adjusted list, correct? So a
regular pull of your list and some tweaking would be the way to go...?

Best regards and thanks a lot for compiling this list!


Am Fr., 1. Apr. 2022 um 12:12 Uhr schrieb Technorabilia <
***@***.***>:

**Comment by technorabilia** [comment]
Yes, you can fork the repo and do a search and replace but then you will not receive any updates automatically anymore.

You can also change the `PUID` & `PGID` from within Portainer before you create the container from the template.

**Comment by technorabilia** [comment]
BTW
You could also use the Docker scripts from [here](https://github.com/technorabilia/docker-bits)  where you can set `PUID` & `PGID` globally.
