### ISSUE TITLE
Generator release

### ISSUE THREAD

**Issue by silopolis** [technorabilia/portainer-templates#7]
Hi,

First thank you for this ! Much valuable and appreciated :pray: 

Thanks to your templates, I was able to add one for Phpmyadmin to @SelfhostedPro 's list for the Yacht Docker management panel.
That was an interesting learning experience... that made me think that, if I had your generator, I could add support for Yacht templates to give back to the community.

Would you release that list generator ?

Thanks again for your work and sharing it with the rest of the world.

**Comment by technorabilia** [comment]
Sure, the generator can be found [here](https://github.com/technorabilia/generate-bits) and a merge tool [here](https://github.com/technorabilia/portainer-tools).

**Comment by silopolis** [comment]
Le sam. 11 juin 2022 à 18:18, Technorabilia ***@***.***> a
écrit :

> Sure, the generator can be found here
> <https://github.com/technorabilia/generate-bits> and a merge tool here
> <https://github.com/technorabilia/portainer-tools>.
>
Awesome !
Thank you so much :pray:

I'll keep you on touch...

Have a very nice weekend  :)
