### ISSUE TITLE
Not working with latest portainer version?

### ISSUE THREAD

**Issue by iamdroppy** [technorabilia/portainer-templates#8]
No app templates are shown if used the 2.0 templates on latest portainer version, and I have no clue where the problem lies to be of any help... JSON is valid, and seems that everything is fine (scheme-wise)

**Comment by technorabilia** [comment]
I've tried it on Portainer CE 2.16.2 and everything seems to work.

In Settings change the App Templates URL to:
`https://raw.githubusercontent.com/technorabilia/portainer-templates/main/lsio/templates/templates-2.0.json`

After that the App Templates are visible:
![image](https://user-images.githubusercontent.com/80631554/207569028-9d1f9ef3-5af1-4744-8351-1a903289d4ca.png)

**Comment by talltechy** [comment]
can confirm working, tested on 2.16.2 with the free BE license applied

**Comment by technorabilia** [comment]
Thanks for confirming @talltechy.

**Comment by Foresterga** [comment]
Same issue.  I am new to this so it is probably something I am missing.  See screenshot.  Once I add the raw template url, I get a message stating "Failure failed to clone git repository: repository not found
![portainer1](https://user-images.githubusercontent.com/95925379/210097998-21a71652-2e8b-4c79-8ead-e3531079dc8a.png)

**Comment by Foresterga** [comment]
portainer version: Community Edition
2.16.2

**Comment by technorabilia** [comment]
@Foresterga 
You should enter the url in the settings like this:
https://docs.portainer.io/admin/settings#app-templates
